spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recime_db
    username: recime_user
    password: recime_password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
