spring:
  jpa:
    hibernate:
      ddl-auto: update # this will not be safe on higher environments, particularly production
  datasource:
    url: jdbc:postgresql://localhost:5432/recime_db
    username: recime_user
    password: recime_password
    driver-class-name: org.postgresql.Driver
